### ISSUE TITLE
Openshift issue with mongock

### ISSUE THREAD

**Issue by fkopriva** [mongock/mongock#411]
I updated mongock version from 4.1.8 to 4.3.8, because of update of mongoDB, and our openshift image can't start now.

**To Reproduce**

I builded image in jenkins and push to openshift 3. Then I deployed new image version and application couldn't start. However I did same thing on local machine and everything is fine.

**Expected behavior**

Openshift env is also running.

**Logs**

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationRunner' defined in com.github.cloudyrock.spring.v5.config.MongockContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner]: Factory method 'applicationRunner' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.bosch.Application$Companion.main(Application.kt:19)
	at com.bosch.Application.main(Application.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner]: Factory method 'applicationRunner' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 28 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.github.cloudyrock.mongock.runner.core.builder.RunnerBuilderBase.addScanItemsFromConfig(RunnerBuilderBase.java:156)
	at com.github.cloudyrock.mongock.runner.core.builder.RunnerBuilderBase.setConfig(RunnerBuilderBase.java:140)
	at com.github.cloudyrock.spring.v5.MongockSpringBuilderBase.setConfig(MongockSpringBuilderBase.java:59)
	at com.github.cloudyrock.spring.v5.MongockSpringBuilderBase.setConfig(MongockSpringBuilderBase.java:28)
	at com.github.cloudyrock.spring.v5.config.MongockContext.getBuilder(MongockContext.java:53)
	at com.github.cloudyrock.spring.v5.config.MongockContext.applicationRunner(MongockContext.java:26)
	at com.github.cloudyrock.spring.v5.config.MongockContext$$EnhancerBySpringCGLIB$$5d72b774.CGLIB$applicationRunner$2(<generated>)
	at com.github.cloudyrock.spring.v5.config.MongockContext$$EnhancerBySpringCGLIB$$5d72b774$$FastClassBySpringCGLIB$$477936b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.github.cloudyrock.spring.v5.config.MongockContext$$EnhancerBySpringCGLIB$$5d72b774.applicationRunner(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 29 common frames omitted`

**Additional context**

I checked all my YML files and configuration is fine. Project is running on Java 11, gradle is used for building. And everything is running fine on old version of mongock.

**Comment by dieppa** [comment]
Hello @fkopriva ,

I am not sure where exactly the errro is coming from, but the exception is because scanPackage list is null. Can you double check you are passing this property?

It's veery weird that is working fine in local, but not in openshift, from the point of view of the exception, it doesn't care about which infrastructure is running o

**Comment by fkopriva** [comment]
`mongock:
    change-logs-scan-package:
      - com.bosch.migrations`
      
this configuration is in all yml files
and all migration files are stored in that package

**Comment by dieppa** [comment]
hey. sorry for the dealay but we won't be able to take a look to this until the end of the week.

Thanks

**Comment by dieppa** [comment]
Hello, we have released 5.0.24 with JDK 17 compatibility. I don't know if this is the case, but it may be worthy to check.

I haven't been able to go in to this issue in detail, will try to do it over the weekend though.

**Comment by fkopriva** [comment]
We are using JDK 11, could that be a problem? That it's not compatible with 4.3.8 version of mongock?

**Comment by dieppa** [comment]
Hello, we have just made a new release. I don't know of anyone experimenting issues with Mongock 4.3.8 o JDK 11. However, I highly recommend using the last version 5.0.29.

Give a shot and let us know 😃

**Comment by dieppa** [comment]
Hello, any new on this regard?

**Comment by nolines** [comment]
@dieppa hey I have the issue but its not on openshift.

here is the related dependency list;
`[INFO] +- com.github.cloudyrock.mongock:mongock-spring-v5:jar:4.3.8:compile
[INFO] |  +- com.github.cloudyrock.mongock:mongock-spring-runner-util:jar:4.3.8:compile
[INFO] |  +- com.github.cloudyrock.mongock:mongock-runner-core:jar:4.3.8:compile
[INFO] |  |  +- com.github.cloudyrock.mongock:mongock-driver-api:jar:4.3.8:compile
[INFO] |  |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.9:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:15.0:compile
[INFO] |  |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  |  \- org.apache.maven:maven-artifact:jar:3.6.1:compile
[INFO] |  |     \- org.codehaus.plexus:plexus-utils:jar:3.2.0:compile
[INFO] |  +- com.github.cloudyrock.mongock:mongock-api:jar:4.3.8:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-configuration-processor:jar:2.5.7:compile
[INFO] |  +- com.github.cloudyrock.mongock:mongock-utils:jar:4.3.8:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.5.7:compile
[INFO] +- com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:jar:4.3.8:compile
[INFO] |  +- com.github.cloudyrock.mongock:mongock-driver-core:jar:4.3.8:compile
[INFO] |  \- com.github.cloudyrock.mongock:mongodb-sync-v4-driver:jar:4.3.8:compile`

java 11. 
spring boot 2.5.7
mongock 4.3.8

**Comment by fkopriva** [comment]
```
spring:
  mongock:
    change-logs-scan-package:
      - com.bosch.migrations
  logging:
    config: classpath:logback.xml
  servlet:
```

So you are telling me that I need to put that mongock config above spring config or just put it as first parameter? I had it as last one. @nolines

**Comment by dieppa** [comment]
Hello @nolines, are you sure the the property is `spring.mongock.change-logs-scan-package`? 

Does it works locally in you dev environment? Or it's on a specific environment?

**Comment by fkopriva** [comment]
it's working on my local env, just had problem with openshift - maybe it's more general problem not only openshift

**Comment by dieppa** [comment]
@fkopriva what it works on your local dev?`mongock...` or `spring.mongock...`?

**Comment by fkopriva** [comment]
spring.mongock...

**Comment by fkopriva** [comment]
Hi, Issue was solved by moving configuration from spring to it's own -
```
from:

spring:
    mongock:
        change-logs-scan-package:
            - com.bosch.migrations

to:

mongock:
    change-logs-scan-package:
        - com.bosch.migrations
spring:
 xxx
```
