### ISSUE TITLE
Cannot inject Spring components in change units with Java 17 + Spring Boot 2.5.6

### ISSUE THREAD

**Issue by dbarjasm** [mongock/mongock#416]
**Describe the bug** 

When the migration runs, it seems to crash because somewhere inside Mongock, there seems to be still a dependency on the old sun package, which should not be used anymore.

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Conditions:
    - Framework and libraries versions: spring-boot-starter-parent v2.5.6
    - Infrastructure: Docker setup with MongoDB and RabbitMQ
    - Mongock version: 5.0.22.RC
    - How Mongock is implemented: annotation approach
    - How Mongock is imported: Part of the pom
 - Steps
    - Just run the application and it crashes when trying to access the injected Spring bean. The proxy that wraps the spring bean seems to be causing the problem.

**Expected behavior**

I can use Spring components without any issues

**Logs**

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.6.jar:2.5.6]
	at be.netmediaeurope.feedprocessor.FeedProcessorApplication.main(FeedProcessorApplication.java:14) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.5.6.jar:2.5.6]
Caused by: io.mongock.api.exception.MongockException: Error in method[V1_AddFeedSecurity.addFeedSecurity] : class io.mongock.driver.api.lock.guard.proxy.LockGuardProxy (in unnamed module @0x10e92f8f) cannot access class sun.reflect.generics.reflectiveObjects.TypeVariableImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x10e92f8f
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processExceptionOnChangeSetExecution(MigrationExecutorBase.java:339) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processSingleChangeSet(MigrationExecutorBase.java:202) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.loopRawChangeSets(MigrationExecutorBase.java:149) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(MigrationExecutorBase.java:143) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processChangeLogInTransactionIfApplies(MigrationExecutorBase.java:143) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processSingleChangeLog(MigrationExecutorBase.java:125) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processChangeLogs(MigrationExecutorBase.java:115) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.lambda$processMigration$1(MigrationExecutorBase.java:110) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processMigration(MigrationExecutorBase.java:110) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeMigration(MigrationExecutorBase.java:97) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeMigration(MigrationExecutorBase.java:40) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.springboot.base.MongockApplicationRunner.run(MongockApplicationRunner.java:18) ~[mongock-springboot-base-5.0.22.RC.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) ~[spring-boot-2.5.6.jar:2.5.6]
	... 10 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.runChangeSet(ChangeLogRuntimeImpl.java:71) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeChangeSetMethod(MigrationExecutorBase.java:329) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeAndLogChangeSet(MigrationExecutorBase.java:239) ~[mongock-runner-core-5.0.22.RC.jar:na]
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processSingleChangeSet(MigrationExecutorBase.java:200) ~[mongock-runner-core-5.0.22.RC.jar:na]
	... 22 common frames omitted
Caused by: java.lang.IllegalAccessError: class io.mongock.driver.api.lock.guard.proxy.LockGuardProxy (in unnamed module @0x10e92f8f) cannot access class sun.reflect.generics.reflectiveObjects.TypeVariableImpl (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x10e92f8f
	at io.mongock.driver.api.lock.guard.proxy.LockGuardProxy.shouldTryProxyReturn(LockGuardProxy.java:33) ~[mongock-driver-api-5.0.22.RC.jar:na]
	at io.mongock.driver.api.lock.guard.proxy.LockGuardProxy.invoke(LockGuardProxy.java:54) ~[mongock-driver-api-5.0.22.RC.jar:na]
	at io.mongock.driver.api.lock.guard.proxy.LockGuardMethodHandler.invoke(LockGuardMethodHandler.java:22) ~[mongock-driver-api-5.0.22.RC.jar:na]
	at be.netmediaeurope.feedprocessor.domain.feed.persistence.FeedDescriptorRepository_$$_mongock_f2c_0.findAll(FeedDescriptorRepository_$$_mongock_f2c_0.java) ~[classes/:na]
```

**Additional context**

I attached the project pom and migration code to this ticket
[issue.zip](https://github.com/mongock/mongock/files/7523700/issue.zip)

**Comment by dieppa** [comment]
Thanks. We'll take a look to it soon.

**Comment by dbarjasm** [comment]
Thank you for the quick feedback :)

**Comment by dieppa** [comment]
Hello @dbarjasm, we have identified the issue,we'll try to locate some time to fix it in the next days.

Thanks

**Comment by dbarjasm** [comment]
Thank you @dieppa, appreciate the quick response times 👍🏻

**Comment by dieppa** [comment]
Hello @dbarjasm , we have release 5.0.23.RC and we have add a pipeline to build and test it with JDK 17, so we can ensure is comptaible.

However, as you probably know maven takes some time to make public the release, so I imagine it will available any time in the next 4 hours.

Regards

**Comment by dbarjasm** [comment]
No problem. As soon as it's available, I'll try it out and provide you with feedback. Thanks again!

**Comment by dieppa** [comment]
It should work, but anything else you need, let us know...and if you can follow as in our [new twitter account](https://twitter.com/MongockTeam), it will be much appreciate it 😄

**Comment by nikhil-nomula** [comment]
Ran into the same issue, works fine in mongock-bom:5.0.23.RC

`
        implementation platform("io.mongock:mongock-bom:5.0.23.RC")
	implementation 'io.mongock:mongock-springboot'
	implementation 'io.mongock:mongodb-springdata-v3-driver'
`

**Comment by dbarjasm** [comment]
I verified it work with version 5.0.24. Thanks @dieppa . The issue can be closed
