### ISSUE TITLE
transactionEnabled property needs to set to false if we enable transactions in spring data

### ISSUE THREAD

**Issue by nikhil-nomula** [mongock/mongock#454]
## Description

We are enabling transactions in spring data via. 

```
@Configuration
@ConditionalOnClass({MongoTransactionManager.class, MongoDatabaseFactory.class})
@EnableConfigurationProperties({MongoProperties.class})
@AutoConfigureAfter({MongoAutoConfiguration.class})
public class CustomMongoTransactionAutoConfiguration {

    @Bean
    MongoTransactionManager transactionManger(MongoDatabaseFactory mongoDatabaseFactory){
        return new MongoTransactionManager(mongoDatabaseFactory);
    }
}

```

As per the[ documentation in mongock ](https://mongock.io/v5/runner/#configuration) -> transaction-enabled indicates whether transaction is enabled. However when I **do not set this to property** or **set it to True**, I run into the following error. 

```

io.mongock.api.exception.MongockException: Error in method[CreateCustomers.execution] : Command failed with error 251 (NoSuchTransaction): 'Transaction 1 has been aborted.' on server localhost:27017. The full response is {"errorLabels": ["TransientTransactionError"], "operationTime": {"$timestamp": {"t": 1639140773, "i": 7}}, "ok": 0.0, "errmsg": "Transaction 1 has been aborted.", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1639140773, "i": 7}}, "signature": {"hash": {"$binary": {"base64": "FLFMQzO0bOCJLjkASvnX8KlyXgY=", "subType": "00"}}, "keyId": 6985530158211923971}}}; nested exception is com.mongodb.MongoCommandException: Command failed with error 251 (NoSuchTransaction): 'Transaction 1 has been aborted.' on server localhost:27017. The full response is {"errorLabels": ["TransientTransactionError"], "operationTime": {"$timestamp": {"t": 1639140773, "i": 7}}, "ok": 0.0, "errmsg": "Transaction 1 has been aborted.", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1639140773, "i": 7}}, "signature": {"hash": {"$binary": {"base64": "FLFMQzO0bOCJLjkASvnX8KlyXgY=", "subType": "00"}}, "keyId": 6985530158211923971}}}
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processExceptionOnChangeSetExecution(MigrationExecutorBase.java:369)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processSingleChangeSet(MigrationExecutorBase.java:203)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.loopRawChangeSets(MigrationExecutorBase.java:150)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(MigrationExecutorBase.java:144)
	at io.mongock.driver.mongodb.springdata.v3.SpringDataMongoV3DriverBase.executeInTransaction(SpringDataMongoV3DriverBase.java:101)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processChangeLogInTransactionIfApplies(MigrationExecutorBase.java:144)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processSingleChangeLog(MigrationExecutorBase.java:126)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processChangeLogs(MigrationExecutorBase.java:116)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.lambda$processMigration$1(MigrationExecutorBase.java:111)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.processMigration(MigrationExecutorBase.java:111)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeMigration(MigrationExecutorBase.java:98)
	at io.mongock.runner.core.executor.operation.change.MigrationExecutorBase.executeMigration(MigrationExecutorBase.java:41)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
	at io.mongock.runner.springboot.base.MongockApplicationRunner.run(MongockApplicationRunner.java:18)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
```

However if I set the transaction-enabled property to false, everything works fine - which is not what the documentation says.. 

```
mongock:
  migration-scan-package:
    - com.test.mongock.changelogs
  transaction-enabled: true
```

## PRIORITY

NORMAL

### Mongock
- Mongock version: 5.0.24
- Modules involved: Spring boot - 2.6.0, Spring data 3.3.0
- How Mongock is used: Annotation approach

### Environment
- Spring boot - 2.6.0, Spring data 3.3.0

## Steps to Reproduce

1. Create a changeset using mongock, in this case the changeset creates records in a collection
2. Run as spring boot app with transaction-enabled property not set or set to true

## Behaviour

**Expected behavior:** Mongock should run fine without any exception as - as per the documentation if this is false, transactions are disabled and will throw an exception. In this case I set it to false and transactions are enabled by spring data. My expectation was that this should run fine without any exception

**Actual behavior:** Throws an exception

**How often the bug happens:** Everytime we run the SB(Spring boot) app

## Link to repository using Mongock

N/A

## Additional context

```
package com.test.mongock.changelogs;

@ChangeUnit(id="create-customers", order = "1", author="nnomula", runAlways = false)
public class CreateCustomers {

    private final CustomerDetailsRepository customerDetailsRepository;

    private static final String CUSTOMERS_COLLECTION = "customers";
    public final static int NO_OF_CUSTOMERS = 10;


    public CreateCustomers(CustomerDetailsRepository customerDetailsRepository) {
        this.customerDetailsRepository = customerDetailsRepository;
    }

    @Execution
    public void execution(CustomerDetailsRepository customerDetailsRepository) {
        customerDetailsRepository.saveAll(
                IntStream.range(0, NO_OF_CUSTOMERS)
                        .mapToObj(i -> {
                            Customer customer = new Customer();
                            customer.setGuestId("profile_id_" + i);
                            customer.setUsername("user_" + i);
                            return customer;
                        })
                        .collect(Collectors.toList()));
    }

    @RollbackExecution
    public void rollbackExecution(CustomerDetailsRepository customerDetailsRepository) {
        customerDetailsRepository.deleteAll();
    }

}

```

**Comment by dieppa** [comment]
Hello @nikhil-nomula,

We'll try to reproduce the error and will let you know.

Thanks

**Comment by dieppa** [comment]
Anyway, you can take a look to[ this example](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot-quickstart)

**Comment by nikhil-nomula** [comment]
Hi @dieppa , I actually found the answer to it in the documentation [here](https://mongock.io/v5/features/transactions/index.html#best-practices) :) 

What I was doing wrong was that I was running DDL operations(Like creating indexes, collations) in the execution method with transaction-enabled: true. 

After looking at the documentation, I moved them from execution method to BeforeExecution method and it works just fine.


The change that I made is 

```
@ChangeUnit(id="create-customers", order = "1", author="nnomula", runAlways = false)
public class CreateCustomers {

    private final CustomerDetailsRepository customerDetailsRepository;

    private static final String CUSTOMERS_COLLECTION = "customers";
    public final static int NO_OF_CUSTOMERS = 10;


    public CreateCustomers(CustomerDetailsRepository customerDetailsRepository) {
        this.customerDetailsRepository = customerDetailsRepository;
    }

    @BeforeExecution
    public void beforeExecution(CustomerDetailsRepository customerDetailsRepository) {
        customerDetailsRepository.saveAll(
                IntStream.range(0, NO_OF_CUSTOMERS)
                        .mapToObj(i -> {
                            Customer customer = new Customer();
                            customer.setCustomerId("customer_id_" + i);
                            customer.setProfileId("profile_id_" + i);
                            customer.setUsername("user_" + i);
                            return customer;
                        })
                        .collect(Collectors.toList()));
    }

    @RollbackBeforeExecution
    public void rollbackBeforeExecution(CustomerDetailsRepository customerDetailsRepository) {
        customerDetailsRepository.deleteAll();
    }

    @Execution
    public void execution(CustomerDetailsRepository customerDetailsRepository) {
       
    }

    @RollbackExecution
    public void rollbackExecution(CustomerDetailsRepository customerDetailsRepository) {
        
    }

}

```

**Note: In this case the collection did not exist, so it is creating the collection(DDL) and then inserting documents into it**
