### ISSUE TITLE
When running a ChangeUnit for DynamoDB, if there are no TransactionItems, Mongock fails

### ISSUE THREAD

**Issue by EnergyPanda** [mongock/mongock#573]
## Description

If a ChangeUnit has no transactionItems, Mongock fails hard when trying to run and fails the start up of Spring Boot.  I have a migration I want to run at every start up checking if tables exist and if they don't, create them.  This results in only table creation, or nothing happening, causing Mongock to do a client.transactWriteItems call, resulting in a Validation error (no transactions).

## PRIORITY

NORMAL

### Mongock
- Mongock version: 5.1.5
- Modules involved(springboot, standalone, MongoDB, DynamoDB, etc.): SpringBoot, DynamoDB
- How Mongock is used(builder or annotation approach, etc.): To check if tables exist on start up, if not, create them

### Environment
- Framework and libraries versions. Especially those that affect directly to Mongock(Spring, Spring data, MongoDB driver, etc.)
- Infrastructure: Kubernetes, Docker, SO, etc.

## Steps to Reproduce

1. Create a ChangeUnit when using DynamoDB and spring boot setup.  Include no TransactionItems when executing
2. Start spring boot service
3. It fails
![Screen Shot 2022-09-09 at 12 04 14 PM](https://user-images.githubusercontent.com/104820212/189325848-f5b2665b-2a06-4818-aa6a-a1d0ee6ba8f4.png)

## Behaviour

**Expected behavior:**
There were no transactions, just finish successfully without failing

**Actual behavior:**
Fails, crashes my spring boot application

**How often the bug happens:**
Every time

## Link to repository using Mongock
Private, sorry.

## Additional context

While AmazonDynamoDb does not want to unmarshall this error for me, through the debugger I can go to this portion of code and determine that line 102 causes a Validation error.  If I add one dummy transactionItem to the ChangeUnit execution, this error does not happen.

![Screen Shot 2022-09-09 at 12 05 17 PM](https://user-images.githubusercontent.com/104820212/189326031-60037b25-b3fa-4a6f-9ee6-d7fbfd89a3f7.png)

**Comment by EnergyPanda** [comment]
I have a fix for this, but I don't seem to have permissions to push.  This is failing:
` git push --set-upstream origin issue/#573_no_transactions_succeeds` - could I get permissions to do this?  Or do I need to do it differently?

**Comment by dieppa** [comment]
Hello @EnergyPanda ,

we will take a look at that issue. Meanwhile your PR is more than welcome. 

However, we follow the standard open source approach for contribution. In summary you need to follow these steps(from this [article](https://opensource.com/article/19/7/create-pull-request-github)) :
1. Find a project you want to contribute to
2. Fork it
3. Clone it to your local system
4. Make a new branch
5. Make your changes
6. Push it back to your repo
7. Click the Compare & pull request button
8. Click Create pull request to open a new pull request

Thanks

**Comment by EnergyPanda** [comment]
Added a PR - I had some trouble with adding tests for this.  Please let me know how to proceed.

**Comment by EnergyPanda** [comment]
Thanks for all your time and help!

Ok, got it.  How long does it usually take from you releasing the code to an update being published to Maven?  I'm just trying to decide for my team if we should block waiting for this or push out with a work-around.

**Comment by dieppa** [comment]
There shouldn't be any problem to have it done released tomorrow. It may be tonight, but I cannot commit to that

**Comment by dieppa** [comment]
Hello @EnergyPanda ,

we have released version 5.1.7 and it should work fine.

Please, take a shoot and update the ticket.

Thanks

**Comment by EnergyPanda** [comment]
I don't see version 5.1.7 [in maven](https://mvnrepository.com/artifact/io.mongock/dynamodb-driver) or [in your release tags](https://github.com/mongock/mongock/tags).  Does it take time for it to propagate?

**Comment by dieppa** [comment]
Sorry, my bad, [5.1.6](https://search.maven.org/artifact/io.mongock/mongock-bom/5.1.6/pom) it's the one

**Comment by EnergyPanda** [comment]
Got it, just verified that this fixes the problem.  Thank you for such a quick turnaround!

**Comment by EnergyPanda** [comment]
Sorry to close this prematurely, I'm actually having a different error now; less problems in general (more than one migration can run fine), but I cannot run my database table creation migration because it still wants a write transaction:

```
Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Value [] at 'transactItems' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 33f928b0-8fc6-49ae-bd30-d6424ef160b4; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6200)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6167)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeTransactWriteItems(AmazonDynamoDBClient.java:5273)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.transactWriteItems(AmazonDynamoDBClient.java:5237)
	at io.mongock.driver.dynamodb.driver.DynamoDBDriverBase.executeInTransaction(DynamoDBDriverBase.kt:102)
	... 88 common frames omitted
```

Do you have any ideas for this?

**Comment by dieppa** [comment]
I would need the changeUnits you are trying to execute.

Also, what happens when you run the application directly(no test or `mvn verify`?

**Comment by EnergyPanda** [comment]
Sorry for the bother! I mixed up the version.  Running with 5.1.6 now, everything works.

**Comment by dieppa** [comment]
Thanks!
