### ISSUE TITLE
Mongock Spring Boot Configuration Startup Error

### ISSUE THREAD

**Issue by CiaranMc93** [mongock/mongock#580]
## Description

Errors during Application Startup

## PRIORITY

NORMAL

### Mongock
- Mongock version
- Modules involved(springboot, standalone, MongoDB, DynamoDB, etc.)
- How Mongock is used(builder or annotation approach, etc.)
Mongock version: 5.1.6
Spring Boot project: 
![image](https://user-images.githubusercontent.com/8858623/195343990-9493cfcd-a4ab-4048-845a-5c8321d37045.png)
Dependencies shown below.
I have used both the annotation and builder approach to no affect. Currently my built project has the @EnableMongock annotation as shown below in screenshots.

### Environment
- Framework and libraries versions. Especially those that affect directly to Mongock(Spring, Spring data, MongoDB driver, etc.)
- Infrastructure: Kubernetes, Docker, SO, etc.

## Steps to Reproduce

1. Run Application

## Behaviour

**Expected behavior:** Mongock should connect to my database and perform the change

**Actual behavior:** I get a configuration error on startup

**How often the bug happens:** 100%

## Additional context
properties file
![image](https://user-images.githubusercontent.com/8858623/195345244-115cfc15-cf34-40dd-8c06-1e573bd5aed5.png)
pom file
![image](https://user-images.githubusercontent.com/8858623/195343171-e9d849df-4f31-4ad1-af8f-660dec8092d1.png)
application file
![image](https://user-images.githubusercontent.com/8858623/195343258-d3da641d-29df-4ab6-8561-79a11045c2b4.png)
ChangeUnit file
![image](https://user-images.githubusercontent.com/8858623/195343433-e7d3a8b9-82ff-4dc1-8b19-381ce99270f1.png)

Error During startup:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'getBuilder' defined in io.mongock.runner.springboot.config.MongockContext: Unsatisfied dependency expressed through method 'getBuilder' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionDriver' defined in class path resource [io/mongock/driver/mongodb/springdata/v3/config/SpringDataMongoV3Context.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command listIndexes requires authentication' on server localhost:27017. The full response is {"operationTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "ok": 0.0, "errmsg": "command listIndexes requires authentication", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "tlgfY6RzGzoLY1Cn6dphF8flEc0=", "subType": "00"}}, "keyId": 7150959439321759746}}}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.4.jar:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.4.jar:2.5.4]
	at ntt.global.platform.migrations.DFDatabaseMigrationsApplication.main(DFDatabaseMigrationsApplication.java:13) ~[classes/:na]
```

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionDriver' defined in class path resource [io/mongock/driver/mongodb/springdata/v3/config/SpringDataMongoV3Context.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command listIndexes requires authentication' on server localhost:27017. The full response is {"operationTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "ok": 0.0, "errmsg": "command listIndexes requires authentication", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "tlgfY6RzGzoLY1Cn6dphF8flEc0=", "subType": "00"}}, "keyId": 7150959439321759746}}}
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.9.jar:5.3.9]
	... 19 common frames omitted
```
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command listIndexes requires authentication' on server localhost:27017. The full response is {"operationTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "ok": 0.0, "errmsg": "command listIndexes requires authentication", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "tlgfY6RzGzoLY1Cn6dphF8flEc0=", "subType": "00"}}, "keyId": 7150959439321759746}}}
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.9.jar:5.3.9]
	... 33 common frames omitted
```
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command listIndexes requires authentication' on server localhost:27017. The full response is {"operationTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "ok": 0.0, "errmsg": "command listIndexes requires authentication", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "tlgfY6RzGzoLY1Cn6dphF8flEc0=", "subType": "00"}}, "keyId": 7150959439321759746}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:358) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:279) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:253) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:345) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:336) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:222) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:171) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:165) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:583) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:165) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.internal.operation.ListIndexesOperation.execute(ListIndexesOperation.java:73) ~[mongodb-driver-core-4.2.3.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:170) ~[mongodb-driver-sync-4.2.3.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135) ~[mongodb-driver-sync-4.2.3.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92) ~[mongodb-driver-sync-4.2.3.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:39) ~[mongodb-driver-sync-4.2.3.jar:na]
	at java.base/java.lang.Iterable.spliterator(Iterable.java:101) ~[na:na]
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.getResidualKeys(MongoSync4RepositoryBase.java:73) ~[mongodb-sync-v4-driver-5.1.6.jar:na]
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.isIndexFine(MongoSync4RepositoryBase.java:62) ~[mongodb-sync-v4-driver-5.1.6.jar:na]
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:49) ~[mongodb-sync-v4-driver-5.1.6.jar:na]
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:40) ~[mongodb-sync-v4-driver-5.1.6.jar:na]
	at io.mongock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:50) ~[mongock-driver-core-5.1.6.jar:na]
	at io.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3ContextBase.connectionDriver(SpringDataMongoV3ContextBase.java:26) ~[mongodb-springdata-v3-driver-5.1.6.jar:na]
	at io.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1196ab89.CGLIB$connectionDriver$2(<generated>) ~[mongodb-springdata-v3-driver-5.1.6.jar:na]
	at io.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1196ab89$$FastClassBySpringCGLIB$$f85b7659.invoke(<generated>) ~[mongodb-springdata-v3-driver-5.1.6.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.9.jar:5.3.9]
	at io.mongock.driver.mongodb.springdata.v3.config.SpringDataMongoV3Context$$EnhancerBySpringCGLIB$$1196ab89.connectionDriver(<generated>) ~[mongodb-springdata-v3-driver-5.1.6.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.9.jar:5.3.9]
```

**Comment by dieppa** [comment]
Hello,
I gather from these lines in logs that your problem is related to MongoDB authentication. 
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command listIndexes requires authentication' on server localhost:27017. The full response is {"operationTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "ok": 0.0, "errmsg": "command listIndexes requires authentication", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1665578351, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "tlgfY6RzGzoLY1Cn6dphF8flEc0=", "subType": "00"}}, "keyId": 7150959439321759746}}}
```

Can you try to run it without Mongock(removing`@EnableMongock` should be enough). It should fail with a similar message.

**Comment by CiaranMc93** [comment]
I removed the @EnableMongock annotation and now the application starts correctly and connects to my local database:

![image](https://user-images.githubusercontent.com/8858623/195348612-c0dbb082-6d79-49fe-a071-96976f14c2f6.png)

2022-10-12 13:56:34.774  INFO 14932 --- [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=33842500, setName='rs-dev', canonicalAddress=devmongo01:27017, hosts=[devmongo01:27017, devmongo03:27017, devmongo02:27017], passives=[], arbiters=[], primary='devmongo01:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000013, setVersion=633340, topologyVersion=null, lastWriteDate=Wed Oct 12 13:56:31 BST 2022, lastUpdateTimeNanos=94978250591300}

**Comment by dieppa** [comment]
What operations have you tried?

The log is pretty clear saying that `command listIndexes requires authentication`. It seams that the MongoTemplate injected to Mongock it's not authenticated.

Can you do the following.
1. Try the command list indexes with MongoTemplate
2. Pass the entire log for the failing case. Not only from the error. Being able to see it from the beginning may help.

Thanks

**Comment by CiaranMc93** [comment]
I had issues with dependencies in my pom file. I have resolved this now.
