### ISSUE TITLE
retryable writes error for mongock-examples/mongodb/standalone-reactive/ example

### ISSUE THREAD

**Issue by arafat0007** [mongock/mongock#618]
## Description
`io.mongock.api.exception.MongockException: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.` is thrown while running mongock provided [mongock-examples/mongodb/standalone-reactive/](https://github.com/mongock/mongock-examples/tree/master/mongodb/standalone-reactive) example  project.

I also added `builder.retryWrites(false);` in `MongoClient buildMongoClientWithCodecs(String connectionString)` method.

## PRIORITY

NORMAL

### Mongock
- same as example  project
- MongoDB standalone instance 5.0.14
- How Mongock is used(builder same as example project)

### Environment
- same as example project
- using MongoDBCompass to run mongodb with the below setups:
URI: mongodb://localhost:27017
In advance connection options,
General > Connection String Scheme = mongodb
General > Host = localhost:27017
Authentication > Authentication Method = None
TLS/SSL = default
Proxy/SSH = None
In-Use Encryption > no changes
Advanced > Read Preference = Default

## Steps to Reproduce

1. starting StandaloneReactiveApp

## Behaviour

**Expected behavior:** 
The following migrations to be executed.

1. io.mongock.examples.mongodb.standalone.reactive.migration.ClientInitializerChangeUnit
2. io.mongock.examples.mongodb.standalone.reactive.migration.ClientUpdaterChangeUnit

**Actual behavior:** 
Error `io.mongock.api.exception.MongockException: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.` is thrown

**How often the bug happens:** 100%

## Link to repository using Mongock
[mongock-examples/mongodb/standalone-reactive/](https://github.com/mongock/mongock-examples/tree/master/mongodb/standalone-reactive) example  project.

## Additional context
What I did extra:

1. I also added `builder.retryWrites(false);` in `MongoClient buildMongoClientWithCodecs(String connectionString)` method.

Trace:
`C:\Users\Arafat\.jdks\openjdk-18.0.2.1\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.2\lib\idea_rt.jar=14699:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath C:\Users\Arafat\Documents\Project_Jware\Mongock\MongockOfficialProject\mongock-examples\mongodb\standalone-reactive\target\classes;C:\Users\Arafat\.m2\repository\io\mongock\mongock-standalone\5.2.4\mongock-standalone-5.2.4.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-standalone-base\5.2.4\mongock-standalone-base-5.2.4.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-runner-core\5.2.4\mongock-runner-core-5.2.4.jar;C:\Users\Arafat\.m2\repository\org\reflections\reflections\0.10.1\reflections-0.10.1.jar;C:\Users\Arafat\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Arafat\.m2\repository\org\apache\maven\maven-artifact\3.6.1\maven-artifact-3.6.1.jar;C:\Users\Arafat\.m2\repository\org\codehaus\plexus\plexus-utils\3.2.0\plexus-utils-3.2.0.jar;C:\Users\Arafat\.m2\repository\org\apache\commons\commons-lang3\3.11\commons-lang3-3.11.jar;C:\Users\Arafat\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongodb-reactive-driver\5.2.4\mongodb-reactive-driver-5.2.4.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-driver-core\5.2.4\mongock-driver-core-5.2.4.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-driver-api\5.2.4\mongock-driver-api-5.2.4.jar;C:\Users\Arafat\.m2\repository\org\javassist\javassist\3.28.0-GA\javassist-3.28.0-GA.jar;C:\Users\Arafat\.m2\repository\org\objenesis\objenesis\3.2\objenesis-3.2.jar;C:\Users\Arafat\.m2\repository\com\google\guava\guava\30.1.1-jre\guava-30.1.1-jre.jar;C:\Users\Arafat\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Arafat\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Arafat\.m2\repository\org\checkerframework\checker-qual\3.8.0\checker-qual-3.8.0.jar;C:\Users\Arafat\.m2\repository\com\google\errorprone\error_prone_annotations\2.5.1\error_prone_annotations-2.5.1.jar;C:\Users\Arafat\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\Arafat\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-utils\5.2.4\mongock-utils-5.2.4.jar;C:\Users\Arafat\.m2\repository\io\mongock\mongock-api\5.2.4\mongock-api-5.2.4.jar;C:\Users\Arafat\.m2\repository\org\mongodb\mongodb-driver-reactivestreams\4.4.1\mongodb-driver-reactivestreams-4.4.1.jar;C:\Users\Arafat\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\Arafat\.m2\repository\io\projectreactor\reactor-core\3.4.12\reactor-core-3.4.12.jar;C:\Users\Arafat\.m2\repository\org\mongodb\bson\4.4.1\bson-4.4.1.jar;C:\Users\Arafat\.m2\repository\org\mongodb\mongodb-driver-core\4.4.1\mongodb-driver-core-4.4.1.jar;C:\Users\Arafat\.m2\repository\org\slf4j\slf4j-api\1.7.32\slf4j-api-1.7.32.jar;C:\Users\Arafat\.m2\repository\org\slf4j\slf4j-simple\1.7.32\slf4j-simple-1.7.32.jar io.mongock.examples.mongodb.standalone.reactive.StandaloneReactiveApp
[main] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[main] INFO io.mongock.runner.core.builder.RunnerBuilderBase - Mongock runner COMMUNITY version[5.2.4]
[main] INFO io.mongock.runner.core.builder.RunnerBuilderBase - Running Mongock with NO metadata
[EVENT LISTENER] - Mongock STARTED successfully
[cluster-rtt-ClusterId{value='6441420c9c28703d56f18042', description='null'}-localhost:27017] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:565}] to localhost:27017
[cluster-ClusterId{value='6441420c9c28703d56f18042', description='null'}-localhost:27017] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:566}] to localhost:27017
[cluster-ClusterId{value='6441420c9c28703d56f18042', description='null'}-localhost:27017] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=37772600}
[Thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:567}] to localhost:27017
[main] INFO org.reflections.Reflections - Reflections took 61 ms to scan 1 urls, producing 2 keys and 2 values
[main] INFO org.reflections.Reflections - Reflections took 1 ms to scan 1 urls, producing 2 keys and 2 values
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock trying to acquire the lock
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock acquired the lock until: Thu Apr 20 22:46:49 JST 2023
[Thread-6] INFO io.mongock.driver.core.lock.LockManagerDefault - Starting mongock lock daemon...
[Thread-3] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:568}] to localhost:27017
[main] INFO io.mongock.runner.core.executor.system.SystemUpdateExecutor - Mongock starting the system update execution id[2023-04-20T22:45:48.617064800-77]...
[main] INFO io.mongock.runner.core.executor.ChangeLogRuntimeImpl - method[io.mongock.runner.core.executor.system.changes.SystemChangeUnit00001] with arguments: []
[main] INFO io.mongock.runner.core.executor.ChangeLogRuntimeImpl - method[beforeExecution] with arguments: [io.mongock.driver.mongodb.reactive.repository.MongoReactiveChangeEntryRepository]
[main] INFO io.mongock.runner.core.executor.ChangeExecutorBase - APPLIED - {"id"="system-change-00001_before", "type"="before-execution", "author"="mongock", "class"="SystemChangeUnit00001", "method"="beforeExecution"}
[main] INFO io.mongock.runner.core.executor.ChangeLogRuntimeImpl - method[execution] with arguments: [io.mongock.driver.mongodb.reactive.repository.MongoReactiveChangeEntryRepository]
[main] INFO io.mongock.runner.core.executor.ChangeExecutorBase - APPLIED - {"id"="system-change-00001", "type"="execution", "author"="mongock", "class"="SystemChangeUnit00001", "method"="execution"}
[main] INFO io.mongock.runner.core.executor.ChangeExecutorBase - Mongock migration aborted and DB transaction not enabled. Starting manual rollback process
[main] INFO io.mongock.runner.core.executor.ChangeLogRuntimeImpl - method[rollbackBeforeExecution] with arguments: []
[main] INFO io.mongock.runner.core.executor.ChangeExecutorBase - ROLLED BACK - {"id"="system-change-00001_before", "type"="before-execution", "author"="mongock", "class"="SystemChangeUnit00001", "method"="beforeExecution"}
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock waiting to release the lock
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock releasing the lock
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock released the lock
[main] ERROR io.mongock.runner.core.executor.system.SystemUpdateExecutor - Mongock has failed executing system updates
[main] INFO io.mongock.runner.core.executor.system.SystemUpdateExecutor - Mongock has finished the system update execution
[main] ERROR io.mongock.runner.core.executor.MongockRunnerImpl - Error in mongock process. ABORTED OPERATION
io.mongock.api.exception.MongockException: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at io.mongock.driver.mongodb.reactive.driver.MongoReactiveDriverBase.executeInTransaction(MongoReactiveDriverBase.java:66)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogInTransactionIfApplies(ChangeExecutorBase.java:147)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeLog(ChangeExecutorBase.java:119)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogs(ChangeExecutorBase.java:107)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processMigration$1(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processMigration(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:76)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:22)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:56)
	at io.mongock.examples.mongodb.standalone.reactive.StandaloneReactiveApp.main(StandaloneReactiveApp.java:14)
Caused by: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at io.mongock.runner.core.executor.ChangeExecutorBase.processExceptionOnChangeSetExecution(ChangeExecutorBase.java:404)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:192)
	at io.mongock.runner.core.executor.ChangeExecutorBase.loopRawChangeSets(ChangeExecutorBase.java:157)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(ChangeExecutorBase.java:147)
	at io.mongock.driver.mongodb.reactive.driver.MongoReactiveDriverBase.executeInTransaction(MongoReactiveDriverBase.java:62)
	... 10 more
Caused by: com.mongodb.MongoClientException: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at com.mongodb.internal.operation.CommandOperationHelper.transformWriteException(CommandOperationHelper.java:613)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$exceptionTransformingCallback$23(CommandOperationHelper.java:627)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.async.function.RetryingAsyncCallbackSupplier$RetryingCallback.onResult(RetryingAsyncCallbackSupplier.java:109)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeBulkWriteBatchAsync$11(MixedBulkWriteOperation.java:414)
	at com.mongodb.internal.async.function.AsyncCallbackLoop$LoopingCallback.onResult(AsyncCallbackLoop.java:72)
	at com.mongodb.internal.async.function.AsyncCallbackLoop$LoopingCallback.onResult(AsyncCallbackLoop.java:61)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeBulkWriteBatchAsync$9(MixedBulkWriteOperation.java:408)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:276)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:82)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:687)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:159)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:528)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:503)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:815)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:782)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:650)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:647)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:284)
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:586)
	at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mongodb.MongoCommandException: Command failed with error 20 (IllegalOperation): 'Transaction numbers are only allowed on a replica set member or mongos' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Transaction numbers are only allowed on a replica set member or mongos", "code": 20, "codeName": "IllegalOperation"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:517)
	... 15 more
Exception in thread "main" io.mongock.api.exception.MongockException: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at io.mongock.driver.mongodb.reactive.driver.MongoReactiveDriverBase.executeInTransaction(MongoReactiveDriverBase.java:66)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogInTransactionIfApplies(ChangeExecutorBase.java:147)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeLog(ChangeExecutorBase.java:119)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogs(ChangeExecutorBase.java:107)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processMigration$1(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processMigration(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:76)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:22)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:56)
	at io.mongock.examples.mongodb.standalone.reactive.StandaloneReactiveApp.main(StandaloneReactiveApp.java:14)
Caused by: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at io.mongock.runner.core.executor.ChangeExecutorBase.processExceptionOnChangeSetExecution(ChangeExecutorBase.java:404)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:192)
	at io.mongock.runner.core.executor.ChangeExecutorBase.loopRawChangeSets(ChangeExecutorBase.java:157)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processChangeLogInTransactionIfApplies$3(ChangeExecutorBase.java:147)
	at io.mongock.driver.mongodb.reactive.driver.MongoReactiveDriverBase.executeInTransaction(MongoReactiveDriverBase.java:62)
	... 10 more
Caused by: com.mongodb.MongoClientException: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
	at com.mongodb.internal.operation.CommandOperationHelper.transformWriteException(CommandOperationHelper.java:613)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$exceptionTransformingCallback$23(CommandOperationHelper.java:627)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.async.function.RetryingAsyncCallbackSupplier$RetryingCallback.onResult(RetryingAsyncCallbackSupplier.java:109)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:95)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeBulkWriteBatchAsync$11(MixedBulkWriteOperation.java:414)
	at com.mongodb.internal.async.function.AsyncCallbackLoop$LoopingCallback.onResult(AsyncCallbackLoop.java:72)
	at com.mongodb.internal.async.function.AsyncCallbackLoop$LoopingCallback.onResult(AsyncCallbackLoop.java:61)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$executeBulkWriteBatchAsync$9(MixedBulkWriteOperation.java:408)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:276)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:82)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:687)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:159)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:528)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:503)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:815)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:782)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:650)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:647)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:284)
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:586)
	at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mongodb.MongoCommandException: Command failed with error 20 (IllegalOperation): 'Transaction numbers are only allowed on a replica set member or mongos' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Transaction numbers are only allowed on a replica set member or mongos", "code": 20, "codeName": "IllegalOperation"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:517)
	... 15 more
[EVENT LISTENER] - Mongock finished with failures

Process finished with exit code 1
`

**Comment by dieppa** [comment]
Sorry we completely missed this one. As it's from a year ago, I assume it's not relevant anymore, so I close it. If you feel otherwise, please re-open it and we'll take a look at it
