### ISSUE TITLE
ClassCastException after upgrading from Mongock 4.1.14 to 5.2.4

### ISSUE THREAD

**Issue by fnordian** [mongock/mongock#619]
## Description

After upgrade to 5.2.4 from 4.1.14, the old changelog cannot be processed anymore. 

## PRIORITY

[CRITICAL]

### Mongock
- Mongock version: 5.2.4
- Modules involved(springboot:3.0.5,MongoDB:4.2)

### Reproduction

1. Create changelog with 4.1.14
2. Upgrade to 5.2.4
3. Run project

## Behaviour

**Expected behavior:** no exception

**Actual behavior:** 
io.mongock.api.exception.MongockException: java.lang.RuntimeException: org.bson.Document cannot be cast to java.util.Date
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:71)
	at io.mongock.runner.springboot.base.MongockApplicationRunner.run(MongockApplicationRunner.java:18)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760)
	... 5 common frames omitted
Caused by: java.lang.RuntimeException: org.bson.Document cannot be cast to java.util.Date
	at io.mongock.utils.DateUtils.toDate(DateUtils.java:23)
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.lambda$getEntriesLog$0(MongoSync4ChangeEntryRepository.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.getEntriesLog(MongoSync4ChangeEntryRepository.java:126)
	at io.mongock.driver.api.entry.ChangeEntryService.getEntriesMap(ChangeEntryService.java:70)
	at io.mongock.driver.api.entry.ChangeEntryService.getExecuted(ChangeEntryService.java:40)
	at io.mongock.runner.core.executor.ChangeExecutorBase.loadExecutedChangeEntries(ChangeExecutorBase.java:437)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:64)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:22)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:56)
	... 7 common frames omitted

**How often the bug happens:** on every startup

**Comment by dieppa** [comment]
Hello @fnordian ,

We are looking at this. It's very strange because this `DateUtils` is a new support we added for LocalDateTime. In older versions of the MongoDB driver, it could only read dates, however they recently added support for "new" Java 8 temporal API. So now we check if it's a date or LocalDateTime, however in your case it seems to be a `Document`.

Could you give me the value in the database of that supposed date, please? Cheers

**Comment by fnordian** [comment]
Hello @dieppa ,


![image](https://user-images.githubusercontent.com/354860/234849563-5eaaa802-10a1-41d8-a62c-1e070a5f86ac.png)

The document is: 
```
{
    "_id" : ObjectId("5f291e43cdbd9b0eec9fb1a9"),
    "executionId" : "2018-10-14T08:14:53.446535-839",
    "changeId" : "init",
    "author" : "",
    "timestamp" : {
        "$date" : "2018-10-14T08:14:53.302Z"
    },
    "state" : "EXECUTED",
    "changeLogClass" : "com...........",
    "changeSetMethod" : "initialSet",
    "executionMillis" : {
        "$numberLong" : "3"
    },
    "_class" : "io.changock.driver.api.entry.ChangeEntry$1"
}
```

**Comment by dieppa** [comment]
Thanks, @fnordian , that helps a lot. We'll fix the bug the soonest we can and will notify you 😃

**Comment by osantana85** [comment]
Hello @fnordian ,

First mention that this wasn't failing in previous versions of Mongock(v4) because although we were storing the data(`timestamp` and `executionMillis`), we weren't reading it. Now, in version 5, we have started to read it and that's producing the error. It's weird that you are the only user experimenting this, though.

Said that, going to the actual technical reason, we have been trying to reproduce the error and the only way is by inserting manually to MongoDB the document you provided. When using the Java driver it saves it as follow(the expected format by Mongock)

```
{
    "_id" : ObjectId("5f291e43cdbd9b0eec9fb1a9"),
    "executionId" : "2018-10-14T08:14:53.446535-839",
    "changeId" : "init",
    "author" : "",
    "timestamp" : ISODate("2018-10-14T08:14:53.302Z"),
    "state" : "EXECUTED",
    "changeLogClass" : "com...........",
    "changeSetMethod" : "initialSet",
    "executionMillis" : NumberLong(3),
    "_class" : "io.changock.driver.api.entry.ChangeEntry$1"
}
```

Please note that fields `timestamp` and `executionMillis` are saved with different format (yours as sub-document).

We think that's due to the fact that you were using an old version of MongoDB or the driver. To discard some possibilities, can you provide the following information?
1) The MongoDB's version used when that changeEntry was inserted(2018-10-14). 
2) The oldest version of MongoDB you have used Mongock with
3) The Java MongoDB driver's version used when that changeEntry was inserted(2018-10-14). 
4) The oldest version of Java MongoDB driver you have used Mongock with
5) Are all the changeUnits  saved with the same format(subdocument with $date/$numberLong)?

**Comment by fnordian** [comment]
The initial MongoDB was 4.0. That's when the first entries have been inserted.

Spring Boot 2.0.3.RELEASE was used. So it should have been mongodb-driver 3.6.4. That's the oldest driver that was used.

More recent changelog entries use `Date` instead of subdocument with $date/$numberLong

**Comment by ev-adias** [comment]
Sorry for hijacking the issue but I'm having a similar problem. We have the migration collection generated I believe from a previous version (I'm inheriting the project) and  we're exporting the data with mongoExport to a DB clone and "executionMillis" does not have the type "NumberLong", only the value. 
We've imported the data but then when Mongock reads the entries it fails with 

`
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')\n\tat org.bson.Document.getLong(Document.java:283)\n\tat io.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.lambda$getEntriesLog$0(MongoSync4ChangeEntryRepository.java:117)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)\n\tat java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)\n\tat java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)\n\tat io.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.getEntriesLog(MongoSync4ChangeEntryRepository.java:120)\n\tat io.mongock.driver.api.entry.ChangeEntryService.getEntriesMap(ChangeEntryService.java:68)\n\tat io.mongock.driver.api.entry.ChangeEntryService.getExecuted(ChangeEntryService.java:38)\n\tat 
`

Looking at the code the only place with a Long is "executionMillis".  It's trying to read into a Long but it's an "Integer" ??
