### ISSUE TITLE
Change Unit is not working with spring boots's annotation @CompoundIndex on entity class

### ISSUE THREAD

**Issue by bedrito** [mongock/mongock#629]
## Description

Change Unit is not working with spring boots's annotation @CompoundIndex

## PRIORITY

[CRITICAL]

## Version and environment
spring boot 3.1.1
mongock 5.3.1

### Mongock
- Mongock version -  5.3.1
- Modules involved - springboot, MongoDB(replica set), spring boot transactions are enabled 
- How Mongock is used - annotation approach

### Environment
- Framework and libraries versions.
  Spring boot - 3.1.1
  Spring data - 4.1.1
  MongoDB driver - 4.9.1

## Steps to Reproduce

1. Create a spring boot entity with the @CompoundIndex annotation
`@CompoundIndex(name = "searchIndex", def = " {'name' : 1}")
@Document(collection = "MyEntity")
public class MyEntity {...}`

2.Define ChangeUnit
`@Execution()
    public void initData(@NonLockGuarded MyEntityService myEntityService) throws IOException {
  
        MyEntity entity = new MyEntity();
        ....
        myEntityService.save(entity);
   }

3. Auto index creation is enabled
4. MongoDB replica set is used and spring transactions are activated. 
5. Execute the change unit.

## Behaviour

**Expected behavior:** to persist my entity successfully

**Actual behavior:** Exception is thrown
`Caused by: com.mongodb.MongoCommandException: Command failed with error 251 (NoSuchTransaction): 'Transaction with { txnNumber: 5 } has been aborted.' on server localhost:58805. The full response is {"errorLabels": ["TransientTransactionError"], "ok": 0.0, "errmsg": "Transaction with { txnNumber: 5 } has been aborted.", "code": 251, "codeName": "NoSuchTransaction", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1688651818, "i": 13}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}, "operationTime": {"$timestamp": {"t": 1688651818, "i": 13}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:443)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:365)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:73)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:204)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:122)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:87)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:297)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:393)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:257)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$0(MixedBulkWriteOperation.java:198)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:358)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:383)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:357)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:383)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:356)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$1(MixedBulkWriteOperation.java:181)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:202)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:76)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1024)
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:1008)
	at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:595)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
	at org.springframework.data.mongodb.SessionAwareMethodInterceptor.invoke(SessionAwareMethodInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
	at jdk.proxy2/jdk.proxy2.$Proxy189.updateOne(Unknown Source)
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$doUpdate$20(MongoTemplate.java:1756)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:600)
	... 103 common frames omitted`

**How often the bug happens:** always

## Additional context
If I remove the @CompoundIndex annotation, it works

**Comment by osantana85** [comment]
Hello @bedrito , we'll take a look and let you know.

**Comment by osantana85** [comment]
Hello @bedrito , your issue seems to be caused by index creation within transaction (not allowed), but we couldn't reproduced it for now, because if we enable `auto index creation`, the entity collection is created (and its related indexes) before the Mongock's execution.

The raised exception was not showing the original cause (was hidden by current transaction aborted exception), so we have just released Mongock's version 5.3.2 which fixes it. 

Could you try it with this new version and print here the exception stack trace?

Thanks.

**Comment by dieppa** [comment]
Hello @bedrito , could you please tell us the reason this is closed? 
Thanks

**Comment by bedrito** [comment]
The problem was caused because of I have added two arrays in compound index and the correct error messages was suspended as @osantana85 mentioned.

**Comment by dieppa** [comment]
Thank you @bedrito
